export const AdminAuditAction = {
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_UNSUSPENDED: 'USER_UNSUSPENDED',
  USER_FORCE_LOGOUT: 'USER_FORCE_LOGOUT',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_PROFILE_EDITED: 'USER_PROFILE_EDITED',
  USER_DATA_EXPORT_TRIGGERED: 'USER_DATA_EXPORT_TRIGGERED',

  ACTIVITY_FORCE_CANCELLED: 'ACTIVITY_FORCE_CANCELLED',
  ACTIVITY_FORCE_DONE: 'ACTIVITY_FORCE_DONE',
  ACTIVITY_SOFT_DELETED: 'ACTIVITY_SOFT_DELETED',
  ACTIVITY_EDITED: 'ACTIVITY_EDITED',
  ACTIVITY_HOST_REASSIGNED: 'ACTIVITY_HOST_REASSIGNED',

  MESSAGE_DELETED: 'MESSAGE_DELETED',

  POST_DELETED: 'POST_DELETED',
  POST_VISIBILITY_CHANGED: 'POST_VISIBILITY_CHANGED',

  REPORT_MARKED_REVIEWED: 'REPORT_MARKED_REVIEWED',
  REPORT_DISMISSED: 'REPORT_DISMISSED',
  REPORT_REASON_CREATED: 'REPORT_REASON_CREATED',
  REPORT_REASON_UPDATED: 'REPORT_REASON_UPDATED',
  REPORT_REASON_DELETED: 'REPORT_REASON_DELETED',

  BLOCK_OVERRIDE: 'BLOCK_OVERRIDE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  FEATURE_FLAG_TOGGLED: 'FEATURE_FLAG_TOGGLED',
  PUSH_BROADCAST_SENT: 'PUSH_BROADCAST_SENT',
} as const;
export type AdminAuditAction =
  (typeof AdminAuditAction)[keyof typeof AdminAuditAction];

export const AdminAuditTargetType = {
  USER: 'USER',
  ACTIVITY: 'ACTIVITY',
  MESSAGE: 'MESSAGE',
  POST: 'POST',
  REPORT: 'REPORT',
  REPORT_REASON: 'REPORT_REASON',
  BLOCK: 'BLOCK',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  FEATURE_FLAG: 'FEATURE_FLAG',
} as const;
export type AdminAuditTargetType =
  (typeof AdminAuditTargetType)[keyof typeof AdminAuditTargetType];
