export const AdminAuditAction = {
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_UNSUSPENDED: 'USER_UNSUSPENDED',
  USER_FORCE_LOGOUT: 'USER_FORCE_LOGOUT',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_PROFILE_EDITED: 'USER_PROFILE_EDITED',
  USER_DATA_EXPORT_TRIGGERED: 'USER_DATA_EXPORT_TRIGGERED',

  ACTIVITY_FORCE_CANCELLED: 'ACTIVITY_FORCE_CANCELLED',
  ACTIVITY_FORCE_DONE: 'ACTIVITY_FORCE_DONE',
  ACTIVITY_SOFT_DELETED: 'ACTIVITY_SOFT_DELETED',
  ACTIVITY_EDITED: 'ACTIVITY_EDITED',
  ACTIVITY_HOST_REASSIGNED: 'ACTIVITY_HOST_REASSIGNED',

  MESSAGE_DELETED: 'MESSAGE_DELETED',

  POST_DELETED: 'POST_DELETED',
  POST_VISIBILITY_CHANGED: 'POST_VISIBILITY_CHANGED',

  REPORT_MARKED_REVIEWED: 'REPORT_MARKED_REVIEWED',
  REPORT_DISMISSED: 'REPORT_DISMISSED',
  REPORT_REASON_CREATED: 'REPORT_REASON_CREATED',
  REPORT_REASON_UPDATED: 'REPORT_REASON_UPDATED',
  REPORT_REASON_DELETED: 'REPORT_REASON_DELETED',

  BLOCK_OVERRIDE: 'BLOCK_OVERRIDE',
  SESSION_REVOKED: 'SESSION_REVOKED',
  FEATURE_FLAG_CREATED: 'FEATURE_FLAG_CREATED',
  FEATURE_FLAG_TOGGLED: 'FEATURE_FLAG_TOGGLED',
  FEATURE_FLAG_EDITED: 'FEATURE_FLAG_EDITED',
  FEATURE_FLAG_DELETED: 'FEATURE_FLAG_DELETED',
  PUSH_BROADCAST_SENT: 'PUSH_BROADCAST_SENT',
  QUEUE_JOB_RETRIED: 'QUEUE_JOB_RETRIED',

  BUSINESS_SUSPENDED: 'BUSINESS_SUSPENDED',
  BUSINESS_UNSUSPENDED: 'BUSINESS_UNSUSPENDED',
  BUSINESS_BOOST_FORCE_CANCELLED: 'BUSINESS_BOOST_FORCE_CANCELLED',
  BUSINESS_AUTO_PAUSE_LIFTED: 'BUSINESS_AUTO_PAUSE_LIFTED',
  BUSINESS_CATEGORY_CREATED: 'BUSINESS_CATEGORY_CREATED',
  BUSINESS_CATEGORY_UPDATED: 'BUSINESS_CATEGORY_UPDATED',
  BUSINESS_CATEGORY_DELETED: 'BUSINESS_CATEGORY_DELETED',

  ADMIN_PAGE_CREATED: 'ADMIN_PAGE_CREATED',
  ADMIN_PAGE_UPDATED: 'ADMIN_PAGE_UPDATED',
  ADMIN_PAGE_PUBLISHED: 'ADMIN_PAGE_PUBLISHED',
  ADMIN_PAGE_UNPUBLISHED: 'ADMIN_PAGE_UNPUBLISHED',
  ADMIN_PAGE_DELETED: 'ADMIN_PAGE_DELETED',
} as const;
export type AdminAuditAction =
  (typeof AdminAuditAction)[keyof typeof AdminAuditAction];

export const AdminAuditTargetType = {
  USER: 'USER',
  ACTIVITY: 'ACTIVITY',
  MESSAGE: 'MESSAGE',
  POST: 'POST',
  REPORT: 'REPORT',
  REPORT_REASON: 'REPORT_REASON',
  BLOCK: 'BLOCK',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  FEATURE_FLAG: 'FEATURE_FLAG',
  QUEUE_JOB: 'QUEUE_JOB',
  BUSINESS: 'BUSINESS',
  BUSINESS_BOOST: 'BUSINESS_BOOST',
  BUSINESS_CATEGORY: 'BUSINESS_CATEGORY',
  ADMIN_PAGE: 'ADMIN_PAGE',
} as const;
export type AdminAuditTargetType =
  (typeof AdminAuditTargetType)[keyof typeof AdminAuditTargetType];
