import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Max,
  Min,
} from 'class-validator';

export class SuggestPlacesDto {
  @ApiProperty({ description: 'Search text', example: 'AMC Lekki' })
  @IsString()
  @Length(1, 256)
  q!: string;

  @ApiPropertyOptional({ example: 6.4541 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(-90)
  @Max(90)
  lat?: number;

  @ApiPropertyOptional({ example: 3.3947 })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(-180)
  @Max(180)
  lng?: number;

  @ApiProperty({
    description:
      'UUIDv4 generated by the client when the picker opens. Send the same value with every suggest + the final retrieve so the provider can bill the whole interaction as one session.',
  })
  @IsUUID('4')
  sessionToken!: string;
}
